# Generated by Django 3.0.5 on 2022-03-21 15:08

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.EmailField(max_length=200)),
                ('account_type', models.CharField(choices=[('USER', 'User'), ('ORG', 'Organization')], default='USER', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrgAccount',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_number', models.IntegerField(unique=True)),
                ('phone_number_confirmed', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.CharField(default='invalid', max_length=6)),
                ('time_of_otp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('otp', models.CharField(default='invalid', max_length=6)),
                ('time_of_otp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_number_confirmed', models.BooleanField(default=False)),
                ('skills', jsonfield.fields.JSONField(null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], default='M', max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('strikes', models.IntegerField(default=0)),
            ],
        ),
    ]
