# Generated by Django 3.0.5 on 2022-03-06 15:51

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone_number_confirmed', models.BooleanField(default=False)),
                ('skills', jsonfield.fields.JSONField(null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], default='M', max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('strikes', models.IntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
    ]
