# Generated by Django 3.0.5 on 2022-03-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20220306_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPVerfification',
            new_name='OTPVerification',
        ),
    ]
