# Generated by Django 3.0.5 on 2022-03-08 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20220308_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('email', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.CharField(default='invalid', max_length=6)),
                ('time_of_otp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
