# Generated by Django 3.0.5 on 2022-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20220308_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='account_type',
            field=models.CharField(choices=[('USER', 'User'), ('ORG', 'Organization')], default='USER', max_length=4),
        ),
    ]
