# Generated by Django 3.0.5 on 2022-03-21 15:08

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('campaign_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organisation_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('skills', jsonfield.fields.JSONField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=1)),
                ('volunteer_count', models.IntegerField(default=1)),
                ('minimum_age', models.IntegerField(default=14)),
                ('status', models.CharField(choices=[('U', 'Upcoming'), ('C', 'Completed')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrgNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('campaign_id', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted')], default='P', max_length=1)),
                ('org_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('campaign_id', models.IntegerField(default=None)),
            ],
        ),
    ]
