# Generated by Django 3.0.5 on 2022-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgView', '0002_auto_20220313_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('campaign_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrgNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('campaign_id', models.IntegerField(default=None)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted')], default='P', max_length=1)),
                ('org_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('campaign_id', models.IntegerField(default=None)),
            ],
        ),
    ]
