# Generated by Django 3.0.5 on 2022-03-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgView', '0003_auto_20220321_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnotif',
            name='org_name',
            field=models.CharField(default='new_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgnotif',
            name='user_name',
            field=models.CharField(default='new_name', max_length=200),
            preserve_default=False,
        ),
    ]
