# Generated by Django 3.0.5 on 2022-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgView', '0004_auto_20220328_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnotif',
            name='campaign_name',
            field=models.CharField(default='new', max_length=200),
            preserve_default=False,
        ),
    ]
