# Generated by Django 3.0.5 on 2022-03-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgView', '0006_auto_20220331_1304'),
        ('OrgView', '0006_auto_20220401_0112'),
    ]

    operations = [
    ]
