# Generated by Django 3.0.5 on 2022-03-21 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercampaign',
            name='date',
        ),
        migrations.RemoveField(
            model_name='usercampaign',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usercampaign',
            name='time',
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
