# Generated by Django 3.0.5 on 2022-03-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0002_auto_20220321_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercampaign',
            name='campaign_name',
            field=models.CharField(default='change this', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='user_name',
            field=models.CharField(default='change this', max_length=200),
            preserve_default=False,
        ),
    ]
