# Generated by Django 3.0.5 on 2022-03-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0003_auto_20220326_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercampaign',
            name='organisation_name',
            field=models.CharField(default='new_name', max_length=200),
            preserve_default=False,
        ),
    ]
