const ERROR_CODE_INVALID_EMAIL = 210;
const ERROR_CODE_EMAIL_IN_USE = 211;
const ERROR_CODE_PHONE_IN_USE = 212;
const ERROR_CODE_WEAK_PASSWORD = 213;
const ERROR_CODE_INVALID_PHONE = 214;
const ERROR_CODE_INVALID_REFRESH_TOKEN = 215;
const ERROR_CODE_INVALID_CREDENTIALS = 216;
const ERROR_CODE_INVAID_JWT_TOKEN = 217;

const ERROR_CODES_REGISTER = [ERROR_CODE_WEAK_PASSWORD, ERROR_CODE_INVALID_EMAIL, ERROR_CODE_EMAIL_IN_USE, ERROR_CODE_INVALID_PHONE, ERROR_CODE_PHONE_IN_USE];

const CustomError = (message: string) => {
    return { response: { data: message } };
};

export { ERROR_CODES_REGISTER, CustomError };
